### ISSUE TITLE
ValueError: '/home/mfdata/var/plugins/<plugin>/...' is not in the subpath of '/home/mfdata/<plugin>' OR one path is relative and the other is absolute.

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/circus_autorestart_plugin#6] opened 2023-12-15 16:00 UTC
In the `circus.log` of the `mfdata` module, there is an error looping indefinitely :
```
2023-12-15 15:53:52 circus[809] [INFO] process: /opt/metwork-mfext-2.2/opt/python3_core/bin/python -c from circus import plugins;plugins.main() --endpoint ipc:///home/mfdata/var/circus.socket --pubsub ipc:///home/mfdata/var/circus_pubsub.socket --config __name__:plugin:autorestart:::stop_signal:9:::stop_children:True:::name:plugin:autorestart circus_autorestart_plugin.CircusAutorestartPlugin launched under pid: 2876
2023-12-15 15:53:53 circus[2876] [INFO] Loading the plugin...
2023-12-15 15:53:53 circus[2876] [INFO] Endpoint: 'ipc:///home/mfdata/var/circus.socket'
2023-12-15 15:53:53 circus[2876] [INFO] Pub/sub: 'ipc:///home/mfdata/var/circus_pubsub.socket'
2023-12-15 15:53:53 circus[2876] [INFO] Starting
2023-12-15 15:53:53 circus_autorestart_plugin[2876] [INFO] watch /home/mfdata/var/plugins/foo
2023-12-15 15:53:53 circus[2876] [INFO] Stopping
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus/plugins/__init__.py", line 262, in main
    plugin.start()
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus/util.py", line 482, in _log
    return func(self, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus/plugins/__init__.py", line 64, in start
    self.initialize()
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus_autorestart_plugin/__init__.py", line 142, in initialize
    self.fill_watchers(debug_output=True)
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus_autorestart_plugin/__init__.py", line 205, in fill_watchers
    monitored_watcher.start_monitoring()
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus_autorestart_plugin/__init__.py", line 65, in start_monitoring
    self.wds = add_inotify_watch(self.inotify_handle, self.working_dir,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus_autorestart_plugin/__init__.py", line 42, in add_inotify_watch
    if not include_function(fullpath):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_circus/lib/python3.11/site-packages/circus_autorestart_plugin/__init__.py", line 96, in include_function
    if ematches(path):
       ^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3/lib/python3.11/site-packages/gitignore_parser.py", line 29, in <lambda>
    return lambda file_path: any(r.match(file_path) for r in rules)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3/lib/python3.11/site-packages/gitignore_parser.py", line 29, in <genexpr>
    return lambda file_path: any(r.match(file_path) for r in rules)
                                 ^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3/lib/python3.11/site-packages/gitignore_parser.py", line 128, in match
    rel_path = str(_normalize_path(abs_path).relative_to(self.base_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_core/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/home/mfdata/var/plugins/foo/python3_virtualenv_sources' is not in the subpath of '/home/mfdata/foo' OR one path is relative and the other is absolute.
```

Reproduced with docker image: **metwork/mfdataplugins-centos8-buildimage:release_2.2**

Create/install two dummy "dev-linked" plugins in mfdata. Then watch the circus log.

**Comment by thebaptiste** [comment] 2023-12-15 23:03
I guess this is something new with Metwork 2.2 ?
It could be related to the use of the last `gitignore-parser` release (0.1.9) in Metwork 2.2...

**Comment by thebaptiste** [comment] 2023-12-16 06:41
Could you test with these versions of `gitignore_parser.py` : 
- https://github.com/mherrmann/gitignore_parser/blob/v0.1.0/gitignore_parser.py (0.1.0, the one used in Metwork 2.1)
- https://github.com/mherrmann/gitignore_parser/blob/v0.1.8/gitignore_parser.py (0.1.8, as there is a change about symlinks in 0.1.9)

**Comment by thebaptiste** [comment] 2023-12-16 07:01
Could you also check that there is a problem only for "dev-linked" plugins ?
By the way, you indicated to create/install **two** of these plugins to reproduce. **One** is not enough ?

**Comment by matthieumarrast** [comment] 2023-12-16 11:26
Yes I think it's new with MetWork 2.2.
One plugin is probably enough to reproduce the issue.
Sorry this time I did not spent enough time on this issue to clearly understand the cause.

**Comment by matthieumarrast** [comment] 2023-12-17 13:14
I checked, and, I don't know why the problem occurs as soon as we bootstrap the second plugin...

**Comment by matthieumarrast** [comment] 2023-12-17 19:13
Indeed bug caused by new version of `gitignore_parser`
Similar to https://github.com/mherrmann/gitignore_parser/issues/29

**Comment by matthieumarrast** [comment] 2023-12-17 19:25
> Could you test with these versions of `gitignore_parser.py` :
> 
> * https://github.com/mherrmann/gitignore_parser/blob/v0.1.0/gitignore_parser.py (0.1.0, the one used in Metwork 2.1)
> * https://github.com/mherrmann/gitignore_parser/blob/v0.1.8/gitignore_parser.py (0.1.8, as there is a change about symlinks in 0.1.9)

With version 0.1.0 in MW 2.2, I face another issue:
```
  File "/opt/metwork-mfext-2.2/opt/python3/lib/python3.11/site-packages/gitignore_parser.py", line 32, in <lambda>
    return lambda file_path: any(r.match(file_path) for r in rules)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3/lib/python3.11/site-packages/gitignore_parser.py", line 32, in <genexpr>
    return lambda file_path: any(r.match(file_path) for r in rules)
                                 ^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3/lib/python3.11/site-packages/gitignore_parser.py", line 143, in match
    if re.search(self.regex, rel_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_core/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_core/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_core/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_core/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_core/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/metwork-mfext-2.2/opt/python3_core/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1
```

**Comment by thebaptiste** [comment] 2023-12-17 21:50
I forgot 0.1.0 was not Python 3.11 compliant (I had to upgrade it when I upgraded Metwork to Python 3.11). Something which was deprecated since a long time in regex became an error with Python 3.11. See [here](https://github.com/python/cpython/issues/91222) or [here](https://github.com/python/cpython/pull/31994/files#diff-78f24041d66ab8ed2ae1aee94bcd42396d27af833cb96a3c506294c6d6dce82d)
Sorry about asking you this useless test.

Could you test with 0.1.8 ?

**Comment by thebaptiste** [comment] 2023-12-17 23:04
https://github.com/mherrmann/gitignore_parser/issues/29 was not fixed in 0.1.0. The fix has been introduced in 0.1.9.
But we didn't have the problem with Metwork 2.1 with 0.1.0 and we have it now with Metwork 2.2 with 0.1.9 ?
I am a little confused...

**Comment by thebaptiste** [comment] 2023-12-18 09:50
It seems to be ok with gitignore-parser 0.1.8
So I think https://github.com/mherrmann/gitignore_parser/pull/59 is wrong (at least for us, maybe there is something to change on our side)

I tried this other fix : https://github.com/excitoon/gitignorefile/commit/88964d418257539b90b19b0f70e052fe7b3fc094 , it seems better to me

By the way, I reproduced the problem with only one "dev-linked" plugin.

**Comment by thebaptiste** [comment] 2023-12-18 09:56
So I will downgrade gitignore-parser to 0.1.8 in Metwork 2.2

**Comment by matthieumarrast** [comment] 2024-01-03 18:15
In its version 0.1.9, `gitignore_parser` (https://github.com/mherrmann/gitignore_parser/blob/master/gitignore_parser.py) decided to not resolve symlinks.

The involved code is line 128: `rel_path = str(_normalize_path(abs_path).relative_to(self.base_path))`
(the `_normalize_path` method does not "resolve" the symbolink link path, whereas before code was `rel_path = str(Path(abs_path).resolve().relative_to(self.base_path))`) with a link resolution.

So it raises an error because our given **abs_path** `/home/mfdata/var/plugins/foo` (a symbolic link) is not "relative_to" the `gitignore_parser` **base path** `/home/mfdata/foo`, computed line 24 with the `resolve()` method, which resolve symbolic link:
```
rule = rule_from_pattern(line, base_path=Path(base_dir).resolve(), source=(full_path, counter))
```

Our plugin path comes from config **working_dir** in `circus.ini` configuration file:
```
[watcher:step.foo.main]
working_dir = /home/mfdata/var/plugins/foo
```
I propose to add a fix to gitignore_parser (solution 1) or in our side (solution 2) we should work with real (resolved) path instead of link path, for the `dev_linked` plugin.

## Solution 1 (gitignore_parser)

In `gitignore_parser.py` replace
```
rule = rule_from_pattern(line, base_path=Path(base_dir).resolve(),  source=(full_path, counter))
```
by
```
rule = rule_from_pattern(line, base_path=_normalize_path(base_dir),  source=(full_path, counter))
```
also, the `base_dir` (where the "ignore" file is located) is not resolved and so the `base_path` will be relative to the `abs_path` wich is also not resolved.

I will test it (IN PROGRESS) and propose a PR if it's OK.

## Solution 2 (metwork)
In **mfplugin** (https://github.com/metwork-framework/mfplugin/tree/master/mfplugin):

In **plugin.py**
=> replaces
```
self.home = os.path.abspath(home)
```
by
```
self.home = str(Path(home).resolve())
```
(add import `from pathlib import Path`)

In **manager.py**, in `_uninstall_plugin` method:
=> replace
```
os.unlink(p.home)
```
by:
```
link_target = os.path.join(self.plugins_base_dir, p.name)
os.unlink(link_target)
```
and
```
if os.path.exists(p.home):
    raise CantUninstallPlugin("can't uninstall plugin: %s "
```
by
```
if os.path.exists(p.home) and not p.is_dev_linked:
    raise CantUninstallPlugin("can't uninstall plugin: %s "
```

I have quikly tested it and it works.
But note that it can have **side effects** !

**Comment by thebaptiste** [comment] 2024-01-08 15:56
I would prefer not to change anything in Metwork !
If you tested it, you could propose a PR to gitignore_parser (solution 1). If necessary, we could fork this repo.

**Closed as completed** 2024-01-20 01:56 UTC
